/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const patient_Logic = require('./code/patient-logic');

class incidentAppSrv extends LCAPApplicationService {
    async init() {

        this.on(['CREATE', 'READ', 'UPDATE'], 'Patient', async (request, next) => {
            await patient_Logic(request);
            return next();
        });

        return super.init();
    }
}


module.exports = {
    incidentAppSrv
};